CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100)  NOT NULL,
    email         VARCHAR(255)  NOT NULL,
    password_hash VARCHAR(100)  NOT NULL,
    phone         VARCHAR(20),
    role          VARCHAR(20)   NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE workshops (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                 VARCHAR(200)  NOT NULL,
    description           VARCHAR(5000) NOT NULL,
    category              VARCHAR(100)  NOT NULL,
    instructor_name       VARCHAR(150)  NOT NULL,
    target_audience       VARCHAR(200)  NOT NULL,
    workshop_date         DATE          NOT NULL,
    start_time            TIME          NOT NULL,
    end_time              TIME          NOT NULL,
    registration_deadline TIMESTAMP     NOT NULL,
    venue                 VARCHAR(255),
    meeting_link          VARCHAR(500),
    capacity              INTEGER       NOT NULL,
    fee                   NUMERIC(10, 2),
    image_url             VARCHAR(500),
    status                VARCHAR(20)   NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_workshops_capacity CHECK (capacity > 0),
    CONSTRAINT ck_workshops_times CHECK (end_time > start_time),
    CONSTRAINT ck_workshops_fee CHECK (fee IS NULL OR fee >= 0),
    CONSTRAINT ck_workshops_location CHECK (venue IS NOT NULL OR meeting_link IS NOT NULL)
);

CREATE INDEX idx_workshops_status_date ON workshops (status, workshop_date);

CREATE TABLE registrations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    workshop_id   BIGINT       NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    cancelled_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_registrations_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_registrations_workshop FOREIGN KEY (workshop_id) REFERENCES workshops (id),
    CONSTRAINT uk_registrations_user_workshop UNIQUE (user_id, workshop_id)
);

CREATE INDEX idx_registrations_workshop_status ON registrations (workshop_id, status);

CREATE TABLE contact_submissions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100)  NOT NULL,
    email      VARCHAR(255)  NOT NULL,
    phone      VARCHAR(20),
    subject    VARCHAR(200)  NOT NULL,
    message    VARCHAR(5000) NOT NULL,
    status     VARCHAR(20)   NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_contact_status_created ON contact_submissions (status, created_at);
